language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get -y install chromium-browser
  - npm install
  - npm rebuild wd
script:
  - npm test
  - npm run test:eslint
  # - npm run test:sauce
  # - npm run build:cordova
notifications:
  email: true
sudo: false

addons:
  sauce_connect: true
  chrome: stable